name: Sanity backup
on:
  schedule:
    - cron: '0 10 */5 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: npx @sanity/cli dataset export production backup.tar.gz
        working-directory: studio
        env:
          SANITY_STUDIO_API_PROJECT_ID: theProjectId
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_BACKUP_TOKEN }}

      - uses: actions/upload-artifact@v2
        with:
          name: production
          path: studio/backup.tar.gz
          retention-days: 5
