cache = true
max_cache_age = "7d"
max_concurrency = 14
max_redirects = 10
max_retries = 2
no_progress = false
output = ".lychee.report.md"
verbose = "trace"

user_agent = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36"

accept = ["200", "429"] # list of accepted status codes for valid links. 
insecure = false # Proceed for server connections considered insecure (invalid TLS).
retry_wait_time = 2 # Minimum wait time in seconds between retries of failed requests.
timeout = 20 # Website timeout from connect to response finished.

# Only test links with the given schemes (e.g. https).
# Omit to check links with any other scheme.
# At the moment, we support http, https, file, and mailto.
scheme = ["https"]

# When links are available using HTTPS, treat HTTP links as errors.
require_https = false

# Request method
method = "get"

# Custom request headers
headers = []

# Remap URI matching pattern to different URI.
# remap = ["https://example.com http://example.invalid"]

base = "https://kollitsch.dev" # Base URL or website root directory to check relative URLs.

# HTTP basic auth support. This will be the username and password passed to the
# authorization HTTP header. See
# <https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization>
# basic_auth = ["example.com user:pwd"]

#############################  Exclusions  ##########################

# Skip missing input files (default is to error if they don't exist).
skip_missing = false

# Check links inside `<code>` and `<pre>` blocks as well as Markdown code
# blocks.
include_verbatim = false

# Ignore case of paths when matching glob patterns.
glob_ignore_case = false

# Exclude URLs and mail addresses from checking (supports regex).
exclude = [
  '^https://www\.linkedin\.com', # 2025-04-11 - blocks bots  # '^https://web\.archive\.org/web/', # 2025-04-11 - blocks bots  # '^https://github\.com', # 2025-04-11 - blocks bots
  # '^https://caniuse\.com', # 2025-04-11 - blocks bots
  # '^https://reddit\.com', # 2025-04-11 - blocks bots
]

# Exclude these filesystem paths from getting checked.
exclude_path = [
  "layouts/",
]

# URLs to check (supports regex). Has preference over all excludes.
include = [
  'gist\.github\.com.*',
]

# Exclude all private IPs from checking.
# Equivalent to setting `exclude_private`, `exclude_link_local`, and
# `exclude_loopback` to true.
exclude_all_private = false

# Exclude private IP address ranges from checking.
exclude_private = false

# Exclude link-local IP address range from checking.
exclude_link_local = false

# Exclude loopback IP address range and localhost from checking.
exclude_loopback = false

# Check mail addresses
include_mail = true
