################################################################################
# https://gohugo.io/getting-started/configuration/#configure-build
################################################################################
useResourceCacheWhen = "never"
writeStats = true
