################################################################################
# see https://gohugo.io/getting-started/configuration/
################################################################################

baseURL = "https://kollitsch.de/"
copyright = "All rights reserved. Copyright &copy;2020 davids-neighbour.com"
defaultContentLanguage = "en"
disableHugoGeneratorInject = true
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
footnoteReturnLinkContents = "^"
googleAnalytics = ""
ignoreErrors = []
languageCode = "en-us"
linenos = true
paginate = "5"
pygmentsUseClasses = true
rssLimit = 10
summaryLength = 70
timeZone = "Asia/Bangkok"
title = "Kollitsch.de"
