################################################################################
# see https://gohugo.io/getting-started/configuration/
################################################################################
baseURL = "https://kollitsch.de/"
copyright = "All rights reserved. Copyright &copy;2021 kollitsch.de"
defaultContentLanguage = "en"
disableHugoGeneratorInject = true
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
footnoteReturnLinkContents = "^"
ignoreErrors = []
languageCode = "en-us"
linenos = true
paginate = "9"
pygmentsUseClasses = true
rssLimit = 10
summaryLength = 40
timeZone = "Asia/Bangkok"
title = "Kollitsch.de"
