################################################################################
# see https://gohugo.io/getting-started/configuration/
################################################################################
baseURL = "https://kollitsch.dev/"
copyright = "All rights reserved. Copyright &copy;2022 kollitsch.dev"
defaultContentLanguage = "en"
disableHugoGeneratorInject = true
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
footnoteReturnLinkContents = "^"
ignoreErrors = []
languageCode = "en-us"
linenos = true
paginate = 10
pygmentsUseClasses = true
rssLimit = 10
summaryLength = 40
timeZone = "Asia/Bangkok"
title = "kollitsch.dev"
# hack: adding a crazy timeout to prevent hugo from... timing out...
timeout = 100000000000000
