################################################################################
# see https://gohugo.io/getting-started/configuration/
################################################################################

baseURL = "https://kollitsch.de/"
copyright = "All rights reserved. Copyright &copy;2020 davids-neighbour.com"
defaultContentLanguage = "en"
disableHugoGeneratorInject = true
enableEmoji = false
enableGitInfo = false
enableRobotsTXT = true
footnoteReturnLinkContents = "^"
languageCode = "en-us"
linenos = true
pygmentsUseClasses = true
rssLimit = 10
summaryLength = 70
timeZone = "Asia/Bangkok"
title = "Kollitsch.de"
ignoreErrors = []
paginate = "5"
googleAnalytics = ""
disableLanguages = ["fr"] # desable language from here
