################################################################################
# see https://gohugo.io/getting-started/configuration/
################################################################################
baseURL = "https://kollitsch.dev/"
defaultContentLanguage = "en"
disableHugoGeneratorInject = true
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
footnoteReturnLinkContents = "^"
ignoreErrors = []
languageCode = "en-us"
linenos = true
paginate = 10
rssLimit = 10
summaryLength = 40
timeZone = "Asia/Bangkok"
title = "KOLLITSCH.dev*"

# hack: adding a crazy timeout to prevent hugo from... timing out...
timeout = 100000000000000
