################################################################################
# see https://gohugo.io/getting-started/configuration/
################################################################################
baseURL = "https://kollitsch.dev/"
defaultContentLanguage = "en"
disableHugoGeneratorInject = true
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
footnoteReturnLinkContents = "^"
ignoreErrors = []
languageCode = "en-us"
linenos = true
paginate = 6
rssLimit = 10
summaryLength = 40
timeZone = "Asia/Bangkok"
title = "KOLLITSCH.dev*"
titleCaseStyle = "chicago"
themes = ["hugo-blockify", "hugo-theme"]

# hack: adding a crazy timeout to prevent hugo from... timing out...
timeout = "60s"
