################################################################################
# see https://gohugo.io/getting-started/configuration/
################################################################################
baseURL = "https://kollitsch.dev/"
defaultContentLanguage = "en"
disableHugoGeneratorInject = true
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
footnoteReturnLinkContents = "^"
languageCode = "en-us"
linenos = true
rssLimit = 10
summaryLength = 15
timeZone = "Asia/Bangkok"
title = "KOLLITSCH.dev*"

################################################################################
# Title style configuration
################################################################################
capitalizeListTitles = false
pluralizeListTitles = false
titleCaseStyle = "chicago"

################################################################################
# error configuration
################################################################################
ignoreErrors = []

################################################################################
# hack: increasing timeout to prevent hugo from... timing out while recreating
# images. this is no more required for this website, because "we got RAM", but
# kept to find it when working on client projects.
# MUST be string, MUST contain digits and s for seconds, probably m for minutes
# (untested)
################################################################################
timeout = "600s"

################################################################################
# pagination - see https://gohugo.io/configuration/pagination/
################################################################################
[pagination]
# disableAliases = false
pagerSize = 10
# path = 'page'

################################################################################
# see https://gohugo.io/getting-started/configuration/#configure-build
################################################################################
[build.buildStats]
enable = true # default is false

################################################################################
# see https://gohugo.io/configuration/imaging/
################################################################################
[imaging]
# Default resample filter used for resizing. Default is Box,
# a simple and fast averaging filter appropriate for downscaling.
# See https://github.com/disintegration/imaging
resampleFilter = "Box"
hint = 'photo'
quality = 90
anchor = "Smart"

[imaging.exif]
# see https://gohugo.io/content-management/image-processing/#exif-data
disableDate = true
disableLatLong = true
excludeFields = ".*"
includeFields = ""

################################################################################
# see https://github.com/yuin/goldmark/#built-in-extensions
# see https://gohugo.io/getting-started/configuration-markup#goldmark
################################################################################
[markup]
[markup.goldmark]

[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = false
linkifyProtocol = "https"
strikethrough = false # needs to be disabled because of extras.subscript and extras.superscript
table = true
taskList = true
# https://gohugo.io/getting-started/configuration-markup/#typographer-extension
typographer = true

# https://gohugo.io/getting-started/configuration-markup/#extras
[markup.goldmark.extensions.extras]
[markup.goldmark.extensions.extras.strikethrough]
enable = true
[markup.goldmark.extensions.extras.insert]
enable = true
[markup.goldmark.extensions.extras.mark]
enable = true
[markup.goldmark.extensions.extras.subscript]
enable = true
[markup.goldmark.extensions.extras.superscript]
enable = true

# https://gohugo.io/content-management/mathematics/
[markup.goldmark.extensions.passthrough]
enable = true
[markup.goldmark.extensions.passthrough.delimiters]
block = [['\[', '\]'], ['$$', '$$']]
inline = [['\(', '\)']]

[markup.goldmark.parser]
autoHeadingID = true
autoHeadingIDType = "github"

[markup.goldmark.parser.attribute]
block = false
title = true

[markup.goldmark.renderer]
hardWraps = false
unsafe = false
xhtml = false

[markup.highlight]
anchorLineNos = true
lineNos = true
lineNumbersInTable = false
# no need for this, we do this in layouts/_default/_markup/render-codeblock.html
# lineAnchors = "code"
codeFences = true
guessSyntax = true
hl_Lines = ""
lineNoStart = 1
noClasses = false
noHl = false
style = "xcode"
tabWidth = 2

[markup.tableOfContents]
endLevel = 4
ordered = false
startLevel = 2

################################################################################
# see https://gohugo.io/configuration/minify/
################################################################################
[minify]
disableCSS = false
disableHTML = false
disableJS = false
disableJSON = false
disableSVG = false
disableXML = true
minifyOutput = false

[minify.tdewolff]

[minify.tdewolff.css]
# deprecated in favour of precision
# decimals = -1
# prohibits using CSS3 syntax (such as exponents in numbers, or rgba( → rgb(), might be incomplete
keepCSS2 = true
# number of significant digits to preserve for numbers, 0 means no trimming
precision = 10

[minify.tdewolff.html]
# preserve all IE conditional comments such as <!--[if IE 6]><![endif]--> and
# <![if IE 6]><![endif]>, see https://msdn.microsoft.com/en-us/library/ms537512(v=vs.85).aspx#syntax
keepConditionalComments = true
# preserve default attribute values such as <script type="application/javascript">
keepDefaultAttrVals = true
# preserve html, head and body tags
keepDocumentTags = true
# preserve all end tags
keepEndTags = true
# preserve quotes around attribute values
keepQuotes = false
# preserve whitespace between inline tags but still collapse multiple whitespace characters into one
keepWhitespace = false
# preserve all comments
keepComments = false

[minify.tdewolff.js]
# keeps variable names as they are and omits shortening variable names
keepVarNames = false
# number of significant digits to preserve for numbers, 0 means no trimming
precision = 10

[minify.tdewolff.json]
# do not minify numbers if set to true, by default numbers will be minified
keepNumbers = false
# number of significant digits to preserve for numbers, 0 means no trimming
precision = 10

[minify.tdewolff.svg]
# number of significant digits to preserve for numbers, 0 means no trimming
precision = 10

[minify.tdewolff.xml]
# preserve whitespace between inline tags but still collapse multiple whitespace characters into one
keepWhitespace = false

################################################################################
# see https://gohugo.io/configuration/outputs/
################################################################################
[outputs]
home = [
  "HTML",
  "security",
  "manifest",
  "REDIR",
  "HEADERS",
  "GISCUS",
  "RSS",
  "jsonfeed",
  "atom",
  "dnblinklist",
  "opensearch",
  "headerimage",
  "modder",
]
page = ["HTML", "headerimage"]
section = ["HTML", "headerimage"]
taxonomy = ["HTML", "headerimage"]
term = ["HTML", "headerimage"]

################################################################################
# see https://gohugo.io/content-management/urls/
################################################################################
[permalinks]
page = "/:title/"

################################################################################
# see https://gohugo.io/configuration/taxonomies/
################################################################################
[taxonomies]
tag = "tags"
keyword = "keywords"
