languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1

############################# English - Main Menu ########################
[[menu.main]]
weight = 1
url = "/"
name = "Home"
  
[[menu.main]]
weight = 3
url = "about"
name = "About"
  
[[menu.main]]
weight = 4
url = "contact"
name = "Contact"

############################# Footer Menu ########################
[[menu.footer]]
weight = 1
url = "about/"
name = "About"

[[menu.footer]]
weight = 2
url = "author/"
name = "Authors"

[[menu.footer]]
weight = 3
url = "privacy/"
name = "Privacy"

[[menu.footer]]
weight = 4
url = "terms-conditions/"
name = "Terms & Conditions"
