languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1

############################# English - Main Menu ########################
[[menu.main]]
weight = 1
url = "/"
name = "Home"
hasChildren = true

  [[menu.main]]
  parent = "Home"
  weight = 1
  url = "homepage/list/"
  name = "List layout"

  [[menu.main]]
  parent = "Home"
  weight = 2
  url = "homepage/grid/"
  name = "Grid layout"
  
[[menu.main]]
weight = 3
url = "about"
name = "About"
  
[[menu.main]]
weight = 4
url = "contact"
name = "Contact"

[[menu.main]]
weight = 5
url = "#"
name = "Pages"
hasChildren = true

  [[menu.main]]
  parent = "Pages"
  weight = 1
  url = "author/"
  name = "Author"
  
  [[menu.main]]
  parent = "Pages"
  weight = 2
  url = "tags/"
  name = "Tags"
  
  [[menu.main]]
  parent = "Pages"
  weight = 3
  url = "tags/photography/"
  name = "Tag Single"
  
  [[menu.main]]
  parent = "Pages"
  weight = 4
  url = "categories/"
  name = "Category"
  
  [[menu.main]]
  parent = "Pages"
  weight = 5
  url = "categories/lifestyle/"
  name = "Category Single"
  
  [[menu.main]]
  parent = "Pages"
  weight = 6
  url = "elements/"
  name = "Elements"

############################# Footer Menu ########################
[[menu.footer]]
weight = 1
url = "about/"
name = "About"

[[menu.footer]]
weight = 2
url = "author/"
name = "Authors"

[[menu.footer]]
weight = 3
url = "privacy/"
name = "Privacy"

[[menu.footer]]
weight = 4
url = "terms-conditions/"
name = "Terms & Conditions"

