[hugoVersion]
extended = true
min = "0.122.0"

[[mounts]]
source = "assets"
target = "assets"

[[mounts]]
source = "package.json"
target = "assets/versions/kollitsch.json"

[[mounts]]
source = "node_modules"
target = "assets/node_modules"

[[imports]]
path = "github.com/davidsneighbour/hugo-theme"
disable = false
ignoreConfig = false
ignoreImports = false

[[imports]]
path = "github.com/davidsneighbour/hugo-modules/modules/debug"

[[imports]]
path = "github.com/davidsneighbour/hugo-modules/modules/hooks"

[[imports]]
path = "github.com/davidsneighbour/hugo-modules/modules/errors"

[[imports]]
path = "github.com/davidsneighbour/hugo-modules/modules/functions"

[[imports]]
path = "github.com/davidsneighbour/hugo-modules/modules/shortcodes"

[[imports]]
path = "github.com/davidsneighbour/hugo-modules/modules/pictures"

[[imports]]
path = "github.com/davidsneighbour/hugo-modules/modules/youtube"

[[imports]]
disable = false
ignoreConfig = true
ignoreImports = true
path = "github.com/csswizardry/ct"

[[imports.mounts]]
source = 'ct.css'
target = 'assets/css/libs/ct.css'

[[imports.mounts]]
source = 'ct.css'
target = 'static/css/libs/ct.css'
