[hugoVersion]
extended = true
min = "0.122.0"

[[mounts]]
source = "assets"
target = "assets"

[[mounts]]
source = "package.json"
target = "assets/versions/kollitsch.json"

[[mounts]]
source = "node_modules"
target = "assets/node_modules"

# Import the theme, for now locally
[[imports]]
path = "nakkhian"
