[hugoVersion]
extended = true
min = "0.94.0"
#max = ""

[[imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = "github.com/dnb-org/dnb-hugo-auditor"

[[imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = "github.com/dnb-org/dnb-hugo-debug"

# [[imports]]
# disable = false
# ignoreConfig = false
# ignoreImports = false
# path = "github.com/dnb-org/dnb-hugo-errors"

[[imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = "github.com/dnb-org/dnb-hugo-feeds"

[[imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = "github.com/dnb-org/dnb-hugo-functions"

[[imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = "github.com/dnb-org/dnb-hugo-giscus"

[[imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = "github.com/dnb-org/dnb-hugo-head"

[[imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = "github.com/dnb-org/dnb-hugo-hooks"

[[imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = "github.com/dnb-org/dnb-hugo-icons"

[[imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = "github.com/dnb-org/dnb-hugo-internals"

[[imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = "github.com/dnb-org/dnb-hugo-netlification"

[[imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = "github.com/dnb-org/dnb-hugo-opensearch"

[[imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = "github.com/dnb-org/dnb-hugo-pictures"

[[imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = "github.com/dnb-org/dnb-hugo-publisher"

[[imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = "github.com/dnb-org/dnb-hugo-pwa"

[[imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = "github.com/dnb-org/dnb-hugo-robots"

[[imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = "github.com/dnb-org/dnb-hugo-search-algolia"

[[imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = "github.com/dnb-org/dnb-hugo-security"

[[imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = "github.com/dnb-org/dnb-hugo-shortcodes"

[[imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = "github.com/dnb-org/dnb-hugo-sitemap"

[[imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = "github.com/dnb-org/dnb-hugo-social"

[[imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = "github.com/dnb-org/dnb-hugo-youtube"
