[hugoVersion]
extended = true
min = "0.111.3"

[[imports]]
path = "hugo-blockify"
disable = false
ignoreConfig = false
ignoreImports = false

[[imports]]
path = "hugo-theme"
disable = false
ignoreConfig = false
ignoreImports = false
