home = [
  "HTML",
  "JSON",
  "security",
  "Algolia",
  "manifest",
  "REDIR",
  "HEADERS",
  "GISCUS",
  "RSS",
  "jsonfeed",
  "atom",
  "dnblinklist",
  "opensearch",
]
page = ["HTML"]
post = ["HTML"]
