home = [
	"HTML",
	"security",
	"manifest",
	"REDIR",
	"HEADERS",
	"GISCUS",
	"RSS",
	"jsonfeed",
	"atom",
	"dnblinklist",
	"opensearch",
]
page = ["HTML"]
# section = [	"HTML", "RSS" ]
# taxonomy = [	"HTML", "RSS" ]
# term = [	"HTML", "RSS" ]
