################################################################################
# see http://gohugo.io/templates/output-formats/
################################################################################
[manifest]
mediaType = "application/manifest+json"
baseName = "manifest"
isPlainText = true
notAlternative = true

[JSON]
mediaType = "application/json"
baseName = "index"
notAlternative = true
isPlainText = true
