################################################################################
# see http://gohugo.io/templates/output-formats/
################################################################################
[JSON]
mediaType = "application/json"
baseName = "index"
notAlternative = true
isPlainText = true

[rss]
baseName = "rss"

[jsonfeed]
mediaType = "application/json"
path = ""
baseName = "feed"
rel = "alternate"
protocol = ""
isPlainText = true
isHTML = false
noUgly = false
permalinkable = false

[atom]
mediaType = "application/rss+xml"
path = ""
baseName = "atom"
rel = "alternate"
protocol = ""
isPlainText = false
isHTML = false
noUgly = true
permalinkable = false

[dnblinklist]
baseName = 'links'
isPlainText = true
mediaType = 'application/json'
permalinkable = false
notAlternative = true

[modder]
baseName = 'modder'
isPlainText = true
mediaType = 'application/json'
notAlternative = true
permalinkable = false
ugly = true
