##################################################################################
# https://gohugo.io/getting-started/configuration/#merge-configuration-from-themes
# some configurations require different merge settings from the default
##################################################################################
_merge = 'deep'

home = [
  "HTML",
  "security",
  "manifest",
  "REDIR",
  "HEADERS",
  "GISCUS",
  "RSS",
  "jsonfeed",
  "atom",
  "dnblinklist",
  "opensearch",
  "headerimage",
  "modder",
]
page = ["HTML", "headerimage"]
section = ["HTML", "headerimage"]
taxonomy = ["HTML", "headerimage"]
term = ["HTML", "headerimage"]
