home = [
  "HTML",
  "security",
  "manifest",
  "REDIR",
  "HEADERS",
  "GISCUS",
  "RSS",
  "jsonfeed",
  "atom",
  "dnblinklist",
  "opensearch",
  "headerimage",
]
page = ["HTML", "headerimage"]
section = ["HTML", "headerimage"]
taxonomy = ["HTML", "headerimage"]
term = ["HTML", "headerimage"]
