################################################################################
# see https://gohugo.io/content-management/urls/
################################################################################

journal = "/journal/:title/"
page = "/:title/"
notes = "/notes/:year/:month/:filename/"
