################################################################################
# see https://gohugo.io/content-management/urls/
################################################################################
page = "/:title/"
