# Note that almost all of these options are regular expression whitelists
# (a string or a slice); the value none will block all.
# see https://gohugo.io/about/security-model/
enableInlineShortcodes = false

[exec]
allow = ['^((dart-)?sass(-embedded)?|go|git|npx|postcss)$']
osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|HOME|TMP|TEMP|TERM)$']

[funcs]
getenv = ['^(HUGO_|REPOSITORY_URL|^BRANCH$)']

[goTemplates]
allowActionJSTmpl = false

[http]
methods = ['(?i)GET|POST']
urls = ['.*']
