# sitemap - @see https://dnbhub.xyz/sitemap
################################################################################

[dnb.sitemap]
enabled = true
# @read https://developers.google.com/search/blog/2023/06/sitemaps-lastmod-ping
format = "2006-01-02"
full = false
#format = "2006-01-02T15:04:05-07:00"
listpages = false

# [[dnb.sitemap.htmlmap.item]]
# type = ".Type"
# section = "blog"
# label = "Blog Posts"

# [[dnb.sitemap.htmlmap.item]]
# type = ".Type"
# section = "components"
# label = "GoHugo Components by DNB"
# sortvalue = ".Title"
# sortdirection = "ASC"

# [[dnb.sitemap.htmlmap.item]]
# type = ".Type"
# section = "tags"
# selection = "in-pages"
# label = "Tags"
# sortvalue = ".Title"
# sortdirection = "ASC"

# [[dnb.sitemap.htmlmap.item]]
# type = ".Type"
# selection = "not-in"
# section = ["blog", "tags", "components"]
# label = "Other pages"
# sortvalue = ".Title"
# sortdirection = "ASC"

[[dnb.sitemap.htmlmap.item]]
label = "Blog Posts"
section = "blog"
type = ".Type"

[[dnb.sitemap.htmlmap.item]]
label = "GoHugo Components by DNB"
section = "gohugo"
sortdirection = "ASC"
sortvalue = ".Title"
type = ".Type"

[[dnb.sitemap.htmlmap.item]]
label = "Tags"
section = "tags"
selection = "in-pages"
sortdirection = "ASC"
sortvalue = ".Title"
type = ".Type"

[[dnb.sitemap.htmlmap.item]]
label = "Other pages"
section = ["blog", "tags", "components"]
selection = "not-in"
sortdirection = "ASC"
sortvalue = ".Title"
type = ".Type"

