################################################################################
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
################################################################################
version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
      day: friday
      time: "22:00"
      timezone: Asia/Bangkok
    assignees:
      - davidsneighbour
    target-branch: main
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: /
    labels:
      - type:dependencies
    ignore:
      # do not update @davidsneighbour packages, that is done via renovate
      - dependency-name: "@davidsneighbour/*"
    cooldown:
      default-days: 5
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
      # include:
      #   - "requests"
      exclude:
        - "@davidsneighbour/*"

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: monthly
      day: friday
      time: "22:00"
      timezone: Asia/Bangkok
    assignees:
      - davidsneighbour
    target-branch: main
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: /
    labels:
      - type:dependencies
    cooldown:
      default-days: 5
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
      # include:
      #   - "requests"
      exclude:
        - "@davidsneighbour/*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      day: friday
      time: "22:00"
      timezone: Asia/Bangkok
    assignees:
      - davidsneighbour
    target-branch: main
    open-pull-requests-limit: 999
    pull-request-branch-name:
      separator: /
    labels:
      - type:dependencies
    cooldown:
      default-days: 5
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
      # include:
      #   - "requests"
      exclude:
        - "@davidsneighbour/*"
