# https://ls-lint.org/2.2/configuration
ls:
  .js: kebab-case
  .ts: kebab-case
  .json: kebab-case
  .jsonc: kebab-case
  .yml: kebab-case

  src/components/**/*:
    .astro: PascalCase
    .test.ts: PascalCase

  src/{pages}/**/*:
    #.astro: kebab-case, but with [parameters] allowed
    .astro: regex:(?:[a-z][a-z0-9]*|\[[a-z][a-z0-9]*(?:-[a-z0-9]+)*\])(?:-(?:[a-z][a-z0-9]*|\[[a-z][a-z0-9]*(?:-[a-z0-9]+)*\]))*


ignore:
  - .git
  - '**/node_modules'
  - .vite
  - .frontmatter
