const config = {
  $schema: "https://biomejs.dev/schemas/2.2.0/schema.json",
  assist: {
    actions: {
      source: {
        organizeImports: "on",
        useSortedKeys: "on",
      },
    },
    enabled: true,
  },
  files: {
    includes: ["**", "!**/.vscode/**/*"],
  },
  formatter: {
    attributePosition: "auto",
    enabled: true,
    formatWithErrors: false,
    includes: ["**", "!**/build", "!**/coverage"],
    indentStyle: "space",
    indentWidth: 2,
    lineEnding: "lf",
    lineWidth: 80,
    useEditorconfig: true,
  },
  html: {
    formatter: {
      enabled: true,
    },
  },
  javascript: {
    formatter: {
      arrowParentheses: "always",
      attributePosition: "auto",
      bracketSameLine: false,
      bracketSpacing: true,
      jsxQuoteStyle: "double",
      quoteProperties: "asNeeded",
      quoteStyle: "double",
      semicolons: "always",
      trailingCommas: "all",
    },
    globals: [
      "Astro",
      "ENVIRONMENT",
      "OffscreenCanvas",
      "onpointerleave",
      "onpointerenter",
      "onemptied",
      "onmouseenter",
      "onkeypress",
      "onloadeddata",
      "oninvalid",
      "onmouseup",
      "onvolumechange",
      "onpointerout",
      "onstorage",
      "onpause",
      "onkeyup",
      "onabort",
      "onanimationstart",
      "onafterprint",
      "onblur",
      "ondurationchange",
      "onwaiting",
      "ondeviceorientation",
      "oncanplaythrough",
      "onclose",
      "onbeforeunload",
      "onanimationend",
      "onmouseleave",
      "oncancel",
      "onseeked",
      "onpointerover",
      "ondragleave",
      "ongotpointercapture",
      "onloadedmetadata",
      "onpageshow",
      "onplay",
      "onunhandledrejection",
      "onbeforeprint",
      "onstalled",
      "oncontextmenu",
      "onreset",
      "onpointercancel",
      "onsubmit",
      "ondrag",
      "onload",
      "onlostpointercapture",
      "onsuspend",
      "ondragstart",
      "onpagehide",
      "onmessage",
      "location",
      "onoffline",
      "onappinstalled",
      "onrejectionhandled",
      "onunload",
      "onwheel",
      "onended",
      "onmousedown",
      "onpointerup",
      "onmouseover",
      "onkeydown",
      "onclick",
      "onfocus",
      "onscroll",
      "onresize",
      "onsearch",
      "ontoggle",
      "oncanplay",
      "onlanguagechange",
      "onpointerdown",
      "ondeviceorientationabsolute",
      "ondragenter",
      "onauxclick",
      "onerror",
      "onpointermove",
      "onmousemove",
      "ondevicemotion",
      "ondrop",
      "onhashchange",
      "onanimationiteration",
      "ondblclick",
      "onratechange",
      "ontransitionend",
      "ondragend",
      "onpopstate",
      "onplaying",
      "onchange",
      "onselect",
      "onbeforeinstallprompt",
      "onmouseout",
      "ontimeupdate",
      "ondragover",
      "oncuechange",
      "onprogress",
      "onloadstart",
      "onseeking",
      "oninput",
      "onmessageerror",
      "onmousewheel",
      "ononline",
    ],
  },
  linter: {
    domains: {
      project: "all",
      test: "all",
    },
    enabled: true,
    includes: ["**", "!src/packages/linting/biome-setup.jsonc"],
    // https://biomejs.dev/linter/javascript/rules/
    rules: {
      complexity: {
        noAdjacentSpacesInRegex: "error",
        noExtraBooleanCast: "error",
        noUselessCatch: "error",
      },
      correctness: {
        noConstAssign: "error",
        noConstantCondition: "error",
        noEmptyCharacterClassInRegex: "error",
        noEmptyPattern: "error",
        noGlobalObjectCalls: "error",
        noInvalidBuiltinInstantiation: "error",
        noInvalidConstructorSuper: "error",
        noNonoctalDecimalEscape: "error",
        noPrecisionLoss: "error",
        noSelfAssign: "error",
        noSetterReturn: "error",
        noSwitchDeclarations: "error",
        noUndeclaredVariables: "error",
        noUnreachable: "error",
        noUnreachableSuper: "error",
        noUnsafeFinally: "error",
        noUnsafeOptionalChaining: "error",
        noUnusedLabels: "error",
        noUnusedPrivateClassMembers: "error",
        noUnusedVariables: "error",
        useIsNan: "error",
        useValidForDirection: "error",
        useValidTypeof: "error",
        useYield: "error",
      },
      performance: {
        noBarrelFile: "error",
        noReExportAll: "error",
      },
      recommended: false,
      suspicious: {
        noAssignInExpressions: "error",
        noAsyncPromiseExecutor: "error",
        noCatchAssign: "error",
        noClassAssign: "error",
        noCompareNegZero: "error",
        noControlCharactersInRegex: "error",
        noDebugger: "error",
        noDuplicateCase: "error",
        noDuplicateClassMembers: "error",
        noDuplicateObjectKeys: "error",
        noDuplicateParameters: "error",
        noEmptyBlockStatements: "error",
        noExplicitAny: "error",
        noFallthroughSwitchClause: "error",
        noFunctionAssign: "error",
        noGlobalAssign: "error",
        noImportAssign: "error",
        noMisleadingCharacterClass: "error",
        noPrototypeBuiltins: "error",
        noRedeclare: "error",
        noShadowRestrictedNames: "error",
        noUnsafeNegation: "error",
        noWith: "error",
        useGetterReturn: "error",
      },
    },
  },
  overrides: [
    {
      includes: ["**/*.html"],
    },
    {
      includes: ["**/*.js", "**/*.ts"],
      javascript: {
        formatter: {
          quoteStyle: "single",
        },
      },
      linter: {
        rules: {
          correctness: {
            // required for Astro components
            // https://biomejs.dev/linter/rules/no-undeclared-variables/
            noUndeclaredDependencies: "off",
            // required for Astro components
            // https://biomejs.dev/linter/rules/no-undeclared-variables/
            noUnusedVariables: "off",
          },
        },
      },
    },
    {
      includes: ["**/*.properties"],
    },
    {
      includes: ["**/*.astro"],
      linter: {
        rules: {
          correctness: {
            // required for Astro components
            // https://biomejs.dev/linter/rules/no-undeclared-variables/
            noUndeclaredDependencies: "off",
            // required for Astro components
            // https://biomejs.dev/linter/rules/no-undeclared-variables/
            noUnusedVariables: "off",
          },
          nursery: {
            noUnresolvedImports: "off",
          },
          style: {
            useConst: "off",
            useImportType: "off",
          },
        },
      },
    },
  ],
  vcs: {
    clientKind: "git",
    defaultBranch: "main",
    enabled: true,
    useIgnoreFile: true,
  },
} as const;

export default config;
