# pwa - @see https://dnbhub.xyz/pwa
################################################################################
[dnb.pwa]
background_color = "#3e3e3e"
description = "This is the online playground of Patrick Kollitsch, David's Neighbour, in Germany produced, digital native living & working on Ko Samui, Thailand."
dev = true
display = "fullscreen"
favicon = "favicon/favicon.png"
short_name = "kollitsch.dev"
theme_color = "#cd3c00"

[[dnb.hooks.filters.pwa."js.buildoptions.params"]]
cached = true
file = 'pwa/buildoptions'
