#!/bin/bash
# v2024.11.24.01

# Exit immediately on any command failure and print commands for debugging
set -e

# load the helper functions
for FILE in ~/github.com/davidsneighbour/dotfiles/bashrc/_lib/*; do
  # shellcheck disable=SC1090 # we check the files for existence and readability
  [[ -f "${FILE}" && -r "${FILE}" ]] && source "${FILE}"
done

# Check for required tools
REQUIRED_TOOLS=(curl sed git)
CURPATH="$(pwd -P)"
SCRIPTPATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Verbosity flag (set to 'true' for verbose output, 'false' for silent mode)
verbose=false

__dnb_check_requirements "${REQUIRED_TOOLS[@]}"
__dnb_load_env
__dnb_create_repopath

# Push release to GitHub
git push origin main --follow-tags

create_ghrelease
