
# robots - @see https://dnbhub.xyz/robots
################################################################################
[dnb.robots]
blockAIBots = true
# initialComment = ""
# concludingComment = ""
disableBranding = false

[[dnb.robots.useragents]]
allow = ["/"]
name = "*"
