
# debug - @see https://dnbhub.xyz/debug
################################################################################
[dnb.debug]
debuglevel = 8
development = true
disablenote = true
enable = false
loglink = "https://dnbql.netlify.app/log"
namespace = "dnb"
package_path = "dnb/%s.json"

[dnb.debug.formats]
datetime = ""
datetime_extended = ""

[dnb.debug.config.plugins.js]
imports = ["import 'debug';"] # es6, in flux

[dnb.debug.config.plugins.scss]
imports = ["scss/_debugprint.scss"]
