
# head - @see https://dnbhub.xyz/head
################################################################################
[dnb.head]
charset = "utf-8"
disable = []
nobase = true
notranslate = false # tell Google not to provide a translation for this document
viewport = "width=device-width, initial-scale=1"
# https://webmonetization.org/docs/getting-started
latitude = "9.578492"
longitude = "99.958311"
monetization = ""
# https://en.wikipedia.org/wiki/ISO_3166
colorschemeOrder = "dark light"
hometitle = "Welcome! This is KOLLITSCH.dev*. The online playground of Patrick Kollitsch, David's Neighbour."
placename = "Koh Samui"
region = "TH-84"
separator = " — "

[dnb.head.fediverse]
creator = '@davidsneighbour@mas.to'

[dnb.head.speedoptimisation]
enable = true # either true or false, or an array of enable options like ["preconnect", "prefetch", "prerender", "preload"]
# careful what you prefetch... this can lead to issues if you preload too much, but can also speed up your site.
# IMHO prefetching all woff(2) fonts is a good idea. Those fonts are supported in all modern browsers.
preconnect = []
prefetch = [
  '/assets/webfonts/jetbrainsmono/jetbrainsmonoi.woff2',
  '/assets/webfonts/jetbrainsmono/jetbrainsmono.woff2',
  '/assets/webfonts/exo/italic.woff2',
  '/assets/webfonts/exo/normal.woff2',
  '/assets/webfonts/anton/regular.woff',
]
prerender = []

[dnb.head.verification]
alexa = ""
bing = ""
google = ""
norton = ""
pinterest = ""
yandex = ""

[dnb.head.styles]
# external, postcss, tailwind
entrypoint = "scss/style.scss"
method = "postcss"

[dnb.head.styles.sassOptions]
# options for the compilation of CSS
# see https://gohugo.io/hugo-pipes/scss-sass/#options
enableSourceMap = true
includePaths = ["node_modules/", "assets/"]
outputStyle = "compressed"
silenceDependencyDeprecations = true
# @TODO fix up silenced deprecations
silenceDeprecations = ["import"]
targetPath = "theme.css"
transpiler = "dartsass"

[dnb.head.styles.postcssOptions]
# see https://gohugo.io/functions/css/postcss/#options
config = "postcss.config.mjs"
# noMap = false
# inlineImports = false
# skipInlineImportsNotFound = false
# options without config file
# use = ""
# parser = ""
# stringifier = ""
# syntax = ""

[dnb.head.styles.tailwindOptions]
# tailwind options, see https://gohugo.io/functions/css/tailwindcss/#options
# minify = false
# optimize = false
# inlineImports = false
# skipInlineImportsNotFound = false
enableSourceMap = "false"
includePaths = ["node_modules/"]
targetPath = "twtheme.css"

[dnb.head.styles.externalOptions]
target = "/styles.css"
