################################################################################
# see https://gohugo.io/configuration/output-formats/
################################################################################
[JSON]
baseName = "index"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[dnblinklist]
baseName = 'links'
isPlainText = true
mediaType = 'application/json'
notAlternative = true
permalinkable = false
