################################################################################
# dnb.renderhooks # @see dnbhub.xyz/renderhooks
################################################################################
[dnb.renderhooks]
[dnb.renderhooks.heading]
disabled = false

[dnb.renderhooks.image]
disabled = false

[dnb.renderhooks.link]
disabled = false

[dnb.renderhooks.config.plugins.js]
imports = ["import './plugins/clipboard.js';"]
