################################################################################
# see https://gohugo.io/getting-started/configuration/
################################################################################
baseURL = "https://192.168.1.201:1313/"
