replacements = 'github.com/davidsneighbour/hugo-functions -> ../../hugo-functions,github.com/davidsneighbour/hugo-search-algolia -> ../../hugo-search-algolia,github.com/davidsneighbour/hugo-tech -> ../../hugo-tech'

[hugoVersion]
extended = true
min = "0.104.3"
#max = ""

[[imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = "github.com/davidsneighbour/hugo-tech"

[[imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = "github.com/davidsneighbour/hugo-auditor"

[[imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = "github.com/davidsneighbour/hugo-debug"

[[imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = "github.com/davidsneighbour/hugo-feeds"

[[imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = "github.com/davidsneighbour/hugo-functions"

[[imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = "github.com/davidsneighbour/hugo-giscus"

# [[imports]]
# disable = true
# ignoreConfig = false
# ignoreImports = false
# path = "github.com/davidsneighbour/hugo-github"

[[imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = "github.com/davidsneighbour/hugo-head"

[[imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = "github.com/davidsneighbour/hugo-hooks"

[[imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = "github.com/davidsneighbour/hugo-icons"

[[imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = "github.com/davidsneighbour/hugo-internals"

[[imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = "github.com/davidsneighbour/hugo-netlification"

[[imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = "github.com/davidsneighbour/hugo-opensearch"

[[imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = "github.com/davidsneighbour/hugo-pictures"

[[imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = "github.com/davidsneighbour/hugo-publisher"

[[imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = "github.com/davidsneighbour/hugo-pwa"

[[imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = "github.com/davidsneighbour/hugo-robots"

[[imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = "github.com/davidsneighbour/hugo-search-algolia"

[[imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = "github.com/davidsneighbour/hugo-security"

[[imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = "github.com/davidsneighbour/hugo-shortcodes"

[[imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = "github.com/davidsneighbour/hugo-sitemap"

[[imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = "github.com/davidsneighbour/hugo-social"

[[imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = "github.com/davidsneighbour/hugo-youtube"
