[hugoVersion]
extended = true
min = "0.111.3"

# importing the modules with them residing in the themes directory.
# better for developing, but might be buggy when deploying, we'll see.
[[imports]]
path = "hugo-blockify"
disable = false
ignoreConfig = false
ignoreImports = false

[[imports]]
path = "hugo-theme"
disable = false
ignoreConfig = false
ignoreImports = false

[[imports]]
path = "github.com/davidsneighbour/hugo-debug"
disable = false
ignoreConfig = false
ignoreImports = false

[[mounts]]
source = "node_modules"
target = "assets/node_modules"
