[default]
check-filename = true
check-file = true
unicode = false
locale = "en-gb"

[default.extend-identifiers]
eq = "eq"
color = "color"
monetization = "monetization"
Acer = "Acer"
idea = "idea"

[files]
extend-exclude = [
  "package-lock.json",
  "CHANGELOG.md",
  "go.sum",
  ".git",
  ".gitignore",
]
ignore-hidden = false
ignore-vcs = true
