name: Lighthouse CI
on:
  push:
  workflow_dispatch:
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v8
        with:
          urls: |
            https://kollitsch.de/
          budgetPath: ./etc/lighthouse/budget.json # test performance budgets
          uploadArtifacts: true
          temporaryPublicStorage: false
          # configPath: ./etc/lighthouse/lighthouserc.json
