[dnb.functions]
loglink = "https://dnbql.netlify.app/log"
namespace = "dnb"

[dnb.functions.setup]
disableNote = false

[dnb.functions.readingtime]
# this must be a float value, not an integer! (no quotation marks and at least
# ending in .0 to typecast it as float)
wordsperminute = 220.0
# should the function return minutes and seconds or only minutes (the latter
# will be rounded up for the seconds in addition).
minutesandseconds = true
