# Listen: https://www.youtube.com/watch?v=dVr8uI2nx5M
################################################################################
# some defaults
################################################################################
_merge = 'deep'
description = "This is the online playground of Patrick Kollitsch, David's Neighbour, in Germany produced, digital native living & working on Koh Samui in Thailand."
# on updating this value add a redirect to data/dnb/netlification/config.toml
mainSections = ["blog", "components", "music", "video"]
mainSection = "blog"

################################################################################
# author setup
################################################################################
[author]
name = "Patrick Kollitsch"
homepage = "https://kollitsch.dev/"
#image = "/images/patrick-kollitsch.jpg"
email = "patrick@kollitsch.de"
#twitter = "davidsneighbour"

# documentation theme setup
################################################################################
[dnb.documentation]
package_path = "dnb/%s.json"

# theme setup
################################################################################
[dnb.theme]
slug = "dark-skies"

# default color scheme (dark/light)
# this is ignored if `dnb.theme.switcher.enabled` is true. In that case the
# value of `dnb.theme.switcher.default` is used.
colorscheme = "dark"

# selected icon theme.
# can be one of the identifiers of the icons module OR
# `specific` to indicate use values of `icon` values as individual classes OR
# `partial` to indicate the inclusion of the value as cached partial
icontheme = "bootstrap"

logo_height = "40"
logo_width = "40"
show_title = true
# contact form works with https://formspree.io or any other email service
# that is listening to POST requests from your local form
contact_form_action = "https://formspree.io/f/xoqyzooe"
repository = "https://github.com/davidsneighbour/kollitsch.dev"

[dnb.theme.tags]
threshold_for_overview = 2

[dnb.theme.contact]
[[dnb.theme.contact.methods]]
label = "Address"
value = '''
Patrick Kollitsch
P.O.Box 10, Post Office Nathon
84140 Suratthani
Thailand
'''
[[dnb.theme.contact.methods]]
label = "Mastodon"
value = "[davidsneighbour@mas.to](https://mas.to/@davidsneighbour)"
[[dnb.theme.contact.methods]]
label = "Telegram"
value = "[davidsneighbour](https://t.me/davidsneighbour)"

# sections setup
[dnb.theme.sections]
[dnb.theme.sections.components]
sort = "lastmod"
[dnb.theme.sections.blog]
sort = "date"

# footer setup
[dnb.theme.footer]
show_version = true
show_tag_as_version = true
show_release_as_version = true
repository = "https://github.com/davidsneighbour/kollitsch.dev"

[dnb.theme.colors]
primary = "#d02d19"

[dnb.theme.dateformat]
long = "Mon, Jan 2, 2006"
short = "Jan 2 2006"
timestamp = "2006-01-02T15:04:05-07:00"

[dnb.theme.switcher]
enabled = true   # boolean
default = "dark" # `dark`, `light` or any theme of `dnb.theme.switcher.themes`

[dnb.theme.backtotop]
enabled = true
icon = "chevron-double-up"

[dnb.theme.jsbuild.options]
# options for the js.Build method
# see https://gohugo.io/hugo-pipes/js/
minify = false
format = "iife"
target = "es2020"
# [dnb.theme.jsbuild.options.externals]
# - "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
# - "node_modules/jquery/dist/jquery.min.js"
# [dnb.theme.jsbuild.options.inject]
# - "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
# - "node_modules/jquery/dist/jquery.min.js"
# [dnb.theme.jsbuild.options.params]
# api = "https://example.org/api"

[dnb.theme.related]
exclude_tags = ["100DaysToOffload"]
limit = 3

################################################################################
# some DNB Org Components Configuration.
#
# @see https://learnxinyminutes.com/docs/toml/ for details about TOML
# @see https://github.com/davidsneighbour/hugo-modules for details about
#      specific module configuration options.
################################################################################

# pictures - @see https://dnbhub.xyz/pictures
################################################################################
[dnb.pictures]
default_image = "images/og_sitewide.png"
default_format = "webp"                  # one of webp, png, jpg
# 16:9, 4:3, 1:1 or whatever ratio you want for thumbnails
# this needs to be a string and needs to be two floats separated by a colon
# aspect_ratio = "16:9"
# changing this requires changes in assets/scss/components/_figure.scss
aspect_ratio = "1.618033:1"
[dnb.pictures.responsive]
# collection of image sizes for responsive image sizes. this takes the aspect_ratio
# above into account, so only the long side length is required here.
[dnb.pictures.responsive.fullwidth]
image_sizes = ["494", "517", "674", "914"]
break_points = ["520", "540", "720", "960"]

[dnb.pictures.responsive.halfwidth]
image_sizes = ["494", "517"]
break_points = ["520", "540"]

# head - @see https://dnbhub.xyz/head
################################################################################
[dnb.head]
latitude = "9.578492"
longitude = "99.958311"
# https://en.wikipedia.org/wiki/ISO_3166
region = "TH-84"
placename = "Koh Samui"
separator = " ↭ "
hometitle = "Welcome on KOLLITSCH.dev*"
disable = []
notranslate = false                     # tell Google not to provide a translation for this document
# https://webmonetization.org/docs/getting-started
monetization = ""
colorschemeOrder = "dark light"

[dnb.head.speedoptimisation]
control = "on" # on/off - off disables all prefetching
prefetch = [
  '/assets/webfonts/jetbrainsmono/jetbrainsmonoi.ttf',
  '/assets/webfonts/jetbrainsmono/jetbrainsmonoi.ttf',
  '/assets/webfonts/jetbrainsmono/jetbrainsmono.ttf',
  '/assets/webfonts/jetbrainsmono/jetbrainsmono.ttf',
  '/assets/webfonts/bahn/bahnpro_regular-webfont.woff2',
  '/assets/webfonts/bahnpro_regular-webfont.woff',
  '/assets/webfonts/bahnpro_regular-webfont.ttf',
  '/assets/webfonts/bahnpro_light-webfont.woff2',
  '/assets/webfonts/bahnpro_light-webfont.woff',
  '/assets/webfonts/bahnpro_light-webfont.ttf',
]
preconnect = []
prerender = []

[dnb.head.verification]
google = ""
yandex = ""
bing = ""
alexa = ""
pinterest = ""
norton = ""

[dnb.head.styles]
method = "postcss"

[dnb.head.styles.options]
# options for the compilation of CSS
# see https://gohugo.io/hugo-pipes/scss-sass/#options
# transpiler = "dartsass"
outputType = "direct"
outputStyle = "compressed"
targetPath = "theme.css"
enableSourceMap = true
includePaths = ["node_modules/", "assets/"]

# social - @see https://dnbhub.xyz/social
################################################################################
[dnb.social]
[dnb.social.sharebuttons]
networks = [
  "rss",
  "buymeacoffee",
  "substack",
  "mastodon",
  "linkedin",
  "instagram",
  "facebook",
  "bluesky",
]

[dnb.social.network.facebook]
url = "https://www.facebook.com/patrick.kollitsch/"
icon = "facebook"
label = "Follow me on Facebook"

[dnb.social.network.bluesky]
url = "https://bsky.app/profile/kollitsch.dev"
icon = "square-fill"
label = "Follow me on Bluesky"

[dnb.social.network.instagram]
url = "https://www.instagram.com/pkollitsch/"
icon = "instagram"
label = "Follow me on Instagram"

[dnb.social.network.linkedin]
url = "https://www.linkedin.com/in/patrickkollitsch/"
icon = "linkedin"
label = "Follow me on LinkedIn"

[dnb.social.network.mastodon]
url = "https://mas.to/@davidsneighbour"
icon = "mastodon"
label = "Me on Mas.to(don)"

[dnb.social.network.rss]
url = "https://kollitsch.dev/rss.xml"
icon = "rss-fill"
label = "Subscribe to RSS feed"

[dnb.social.network.buymeacoffee]
url = "https://www.buymeacoffee.com/davidsneigbour"
icon = "cup-hot-fill"
label = "Buy me a coffee"

[dnb.social.network.substack]
url = "https://davidsneighbour.substack.com/"
icon = "stack"
label = "Follow me on Substack"

[dnb.social.twitter]
profile = "davidsneighbour"
domain = "davids-neighbour.com"

# giscus - @see https://dnbhub.xyz/giscus
################################################################################
[dnb.giscus]
#src="https://dnb-comm.vercel.app/client.js"
dataRepo = "davidsneighbour/kollitsch.dev"
dataRepoId = "MDEwOlJlcG9zaXRvcnk0MDU5MjUzNTE="
dataCategory = "Comments"
dataCategoryId = "DIC_kwDOGDHt584B_i3-"
dataMapping = "specific"
dataReactionsEnabled = "1"
dataEmitMetadata = "0"
#dataThemeType = "local"
#dataTheme = "/assets/giscus.css"
#dataTheme = "preferred_color_scheme"
dataLoading = "lazy"

[dnb.giscus.extended]
defaultCommentOrder = "oldest"
origins = ["htttps://kollitsch.dev", "http://192.168.1.201:1313"]

# security - @see https://dnbhub.xyz/security
################################################################################
[dnb.security.txt]
intro = '''
##############################################################################
#                                                                            #
# Information related to reporting security vulnerabilities on kollitsch.dev #
#                                                                            #
#                        ,     ,                                             #
#                       (\____/)                                             #
#                        (_oo_)                                              #
#                          (O)                                               #
#                        __||__    \)                                        #
#                     []/______\[] /                                         #
#                     / \______/ \/                                          #
#                    /    /__\                                               #
#                   (\   /____\                                              #
#                                                                            #
#                                                                            #
##############################################################################
'''
contact = "https://kollitsch.dev/contact/"
expires = 365
languages = "en,de"
policy = "https://davids-neighbour.com/security-policy/"

# debug - @see https://dnbhub.xyz/debug
################################################################################
[dnb.debug]
enable = false
disablenote = true
debuglevel = 1

# pwa - @see https://dnbhub.xyz/pwa
################################################################################
[dnb.pwa]
dev = true
short_name = "kollitsch.dev"
theme_color = "#cd3c00"
background_color = "#3e3e3e"
display = "fullscreen"
description = "This is the online playground of Patrick Kollitsch, David's Neighbour, in Germany produced, digital native living & working on Ko Samui, Thailand."

# robots - @see https://dnbhub.xyz/robots
################################################################################
[dnb.robots]
disableBranding = true
initialComment = '''
#                  ,--.    ,--.
#                 ((O ))--((O ))
#               ,|_`--|____`--|_`.
#              _:  ____________  :_
#             | | ||==========|| | |
#             | | ||==========|| | |
#             | | ||==========|| | |
#             |_| |/__________\| |_|
#               |________________|
#            __..-|kollitsch.dev|-..__
#         .-| : .----------------. : |-.
#       ,\ || | |\______________/| | || /.
#      /`.\:| | ||  __  __  __  || | |;/,|\
#     :`-._\;.| || |--||--||--| || |,:/_.-|:
#     |    :  | || .----------. || |  :    |
#     |    |  | || |---XXXX---| || |  |    |
#     |    |  | ||   _   _   _  || |  |    |
#     :.--.:  | ||  (_) (_) (_) || |  :.--.:
#     (|-||)  | ||______________|| |  (||-|)
#      \--/   | |/______________\| |   \--/
#             |____________________|
#              `.________________,|
#               (_______)(_______)
#               (_______)(_______)
#               (_______)(_______)
#               (_______)(_______)
#              |        ||        |
#              |--------||--------|
'''

# [[dnb.robots.useragents]]
# name = "*"
# # https://developers.cloudflare.com/fundamentals/get-started/reference/cdn-cgi-endpoint/
# disallow = ["/cdn-cgi/"]

# [[dnb.robots.useragents]]
# name = "GPTBot"
# disallow = ["/"]

# sitemap - @see https://dnbhub.xyz/sitemap
################################################################################
[[dnb.sitemap.htmlmap.item]]
type = ".Type"
section = "blog"
label = "Blog Posts"

[[dnb.sitemap.htmlmap.item]]
type = ".Type"
section = "components"
label = "GoHugo Components by DNB"
sortvalue = ".Title"
sortdirection = "ASC"

[[dnb.sitemap.htmlmap.item]]
type = ".Type"
section = "tags"
selection = "in-pages"
label = "Tags"
sortvalue = ".Title"
sortdirection = "ASC"

[[dnb.sitemap.htmlmap.item]]
type = ".Type"
selection = "not-in"
section = ["blog", "tags", "components"]
label = "Other pages"
sortvalue = ".Title"
sortdirection = "ASC"

# netlification - @see https://dnbhub.xyz/netlification
################################################################################
[dnb.netlification]
headers = [
  # "Access-Control-Allow-Origin: *",
  "Report-To: {\"group\":\"default\",\"max_age\":31536000,\"endpoints\":[{\"url\":\"https://kollitsch.report-uri.com/a/d/g\"}],\"include_subdomains\":true}",
  "NEL: {\"report_to\":\"default\",\"max_age\":31536000,\"include_subdomains\":true}",
]
upgradeInsecureRequests = true
mode = "netlify"
extensions = ["youtube", "cloudflare.insights"]

[dnb.netlification.csp]
reportOnly = false
reportUri = "https://kollitsch.report-uri.com/r/d/csp/enforce"

#require-trusted-types-for = ["'script'"]
upgradeInsecureRequests = true
base-uri = ["'self'"]
default-src = ["'none'"]
script-src = [
  "'self'",
  "'unsafe-eval'",
  "'unsafe-inline'",
  "'wasm-unsafe-eval'",
  #"'strict-dynamic'",
  "https://d33wubrfki0l68.cloudfront.net",
  "https://giscus.app/",
  'https://unpkg.com',
  "https://identity.netlify.com",
  #"'nonce-dnb-components-sw'",
  "static.cloudflareinsights.com",
  "www.googletagmanager.com/gtag/js",
]
style-src = [
  "'self'",
  "'unsafe-inline'",
  "https://d33wubrfki0l68.cloudfront.net",
  "https://giscus.app/",
]
img-src = [
  "'self'",
  "https://d33wubrfki0l68.cloudfront.net",
  "data:",
  "https://i.ytimg.com",
]
font-src = ["'self'", "https://d33wubrfki0l68.cloudfront.net"]
connect-src = [
  "'self'",
  "https://api.github.com/",
  'cloudflareinsights.com',
  "www.google-analytics.com",
]
media-src = ["'self'"]
object-src = ["'none'"]
child-src = ["'self'"]
frame-src = [
  "'self'",
  "https://giscus.app/",
  "https://www.youtube-nocookie.com",
]
frame-ancestors = ["'self'"]
worker-src = ["'self'"]
form-action = ["'self'", "https://formspree.io/f/xoqyzooe"]
manifest-src = ["'self'"]

[[dnb.netlification.redirects]]
netlify = "https://kollitsch-dev.netlify.app/"

[[dnb.netlification.redirects]]
from = "/_schemata"
to = "https://kollitsch.dev"
status = "301"

[[dnb.netlification.redirects]]
from = "/repos/*"
to = "https://kollitsch.dev/"
status = "301"

[[dnb.netlification.redirects]]
from = "/2005/*"
to = "https://kollitsch.dev/"
status = "301"

[[dnb.netlification.redirects]]
from = "/2006/*"
to = "https://kollitsch.dev/"
status = "301"

[[dnb.netlification.redirects]]
from = "/2007/*"
to = "https://kollitsch.dev/"
status = "301"

[[dnb.netlification.redirects]]
from = "/2008/*"
to = "https://kollitsch.dev/"
status = "301"

[[dnb.netlification.redirects]]
from = "/tags/kollitsch.de/"
to = "https://kollitsch.dev/tags/davidsneighbour/"
status = "301"

[[dnb.netlification.redirects]]
from = "/tags/dnb/"
to = "https://kollitsch.dev/tags/davidsneighbour/"
status = "301"

[[dnb.netlification.redirects]]
from = "/tags/dnb-org/"
to = "https://kollitsch.dev/tags/davidsneighbour/"
status = "301"

[[dnb.netlification.redirects]]
from = "/repos/textpattern-plugins/current/"
to = "https://kollitsch.dev/"
status = "301"

[[dnb.netlification.redirects]]
from = "/dnb/*"
to = "https://kollitsch.dev/"
status = "301"

[[dnb.netlification.redirects]]
from = "/repos/textpattern-plugins/current/"
to = "https://kollitsch.dev/"
status = "301"

[[dnb.netlification.redirects]]
from = "/blog/2021/gitignore-for-gohugo/"
to = "/blog/2022/gitignore-gohugo/"
status = "301"

[[dnb.netlification.redirects]]
from = "/blog/2022/100daystooffload/"
to = "/blog/2022/100-days-to-offload/"
status = "301"

[[dnb.netlification.redirects]]
from = "/blog/2023/saving-github-access-token-in-local-encrypted-storage-via-gh-cli/header_hu73d41e50f6d7c72e043341b75404e1ba_67194_1200x630_resize_q70_lanczos.jpg"
to = "https://kollitsch.dev/"
status = "301"

# hooks - @see https://dnbhub.xyz/hooks
################################################################################
[dnb.hooks]
debug = true

[[dnb.hooks.items.theme.body-main-end]]
file = "body-main-end"
cached = false

[[dnb.hooks.items.theme.head-post-css]]
file = "head-post-css"
cached = false

[[dnb.hooks.items.theme.head-pre-css]]
file = "head-pre-css"
cached = true

[[dnb.hooks.items.theme.head-start]]
file = "head-start"
cached = true

[[dnb.hooks.items.theme.header-topnav-pre]]
file = "header-topnav-pre"
cached = false

[[dnb.hooks.items.theme.post-after]]
file = "post-after"
cached = false

[[dnb.hooks.items.theme.head-post-css]]
file = "head-post-css"
cached = false
