################################################################################
# see https://gohugo.io/getting-started/configuration/
################################################################################

baseURL = "https://kollitsch.de/"
copyright = "All rights reserved. Copyright &copy;2020 davids-neighbour.com"
defaultContentLanguage = "en"
disableHugoGeneratorInject = true
enableEmoji = false
enableGitInfo = false
enableRobotsTXT = true
footnoteReturnLinkContents = "^"
googleAnalytics = "UA-400066-25"
languageCode = "en-us"
linenos = true
pygmentsUseClasses = true
rssLimit = 10
summaryLength = 70
timeZone = "Asia/Bangkok"
title = "David's Neighbour"
