[hugoVersion]
extended = false
min = "0.84.4"

[[mounts]]
source = "assets"
target = "assets"

# [[mounts]]
# source = "content"
# target = "content"

[[mounts]]
source = "data"
target = "data"

[[mounts]]
source = "i18n"
target = "i18n"

[[mounts]]
source = "layouts"
target = "layouts"

[[mounts]]
source = "static"
target = "static"

# [[imports]]
# path = "github.com/twbs/icons"
# disable = false
# ignoreConfig = true
# ignoreImports = true

# [[imports.mounts]]
# source = "icons"
# target = "assets/icons/bootstrap-icons"

# [[imports]]
# path = "github.com/tailwindlabs/heroicons"
# disable = false
# ignoreConfig = true
# ignoreImports = true

# [[imports.mounts]]
# source = "optimized/outline"
# target = "assets/icons/heroicons/24/outline"

# [[imports.mounts]]
# source = "optimized/solid"
# target = "assets/icons/heroicons/24/solid"

# [[imports]]
# path = "github.com/tabler/tabler-icons"
# disable = false
# ignoreConfig = true
# ignoreImports = true

# [[imports.mounts]]
# source = "src/_icons"
# target = "assets/icons/tabler-icons"

# [[imports]]
# disable = false
# ignoreConfig = true
# ignoreImports = true
# path = "github.com/csswizardry/ct"

# [[imports.mounts]]
# source = 'ct.css'
# target = 'assets/css/libs/ct.css'

# [[imports.mounts]]
# source = 'ct.css'
# target = 'static/css/libs/ct.css'

# [[imports]]
# path = "github.com/davidsneighbour/lazysizes"
# disable = false
# ignoreConfig = true
# ignoreImports = true

# [[imports.mounts]]
# source = "lazysizes-umd.js"
# target = "assets/libs/lazysizes/index.js"

# [[imports.mounts]]
# source = "lazysizes.js"
# target = "assets/libs/lazysizes/lazysizes.js"

# [[imports.mounts]]
# source = "plugins"
# target = "assets/libs/lazysizes/plugins"
