
# pictures - @see https://dnbhub.xyz/pictures
################################################################################
[dnb.pictures]
# webp requires the extended gohugo version
default_format = "jpg" # one of webp, png, jpg
default_image = "images/og_sitewide.png"
# 16:9, 4:3, 1:1 or whatever ratio you want for thumbnails
# this needs to be a string and needs to be two floats separated by a colon
# aspect_ratio = "16:9"
# changing this requires changes in assets/scss/components/_figure.scss
aspect_ratio = "1.618033:1"
[dnb.pictures.responsive]
# collection of image sizes for responsive image sizes. this takes the aspect_ratio
# above into account, so only the long side length is required here.
[dnb.pictures.responsive.fullwidth]
break_points = ["520", "540", "720", "960"]
image_sizes = ["494", "517", "674", "914"]

[dnb.pictures.responsive.halfwidth]
break_points = ["520", "540"]
image_sizes = ["494", "517"]
