[[contentOption]]
value = "post"
label = "Post"
kind = "blog"
path = "blog/${year}/${slug}"

[[contentOption]]
value = "video"
label = "Video Post"
kind = "video"
path = "blog/${year}/${slug}"

[[contentOption]]
value = "m2p2"
label = "Music to program to"
kind = "music2program2"
counter = "data/dnb/kollitsch/m2p2.json"
path = "blog/${year}/music-to-program-to-${counter}"
customSlug = false

[[contentOption]]
value = "kurzschnitte"
label = "Kurzschnitte"
kind = "kurzschnitte"
counter = "data/dnb/kollitsch/kurzschnitt-counter.json"
path = "blog/${year}/kurzschnitte-ii-${counter}"
customSlug = false

[[contentOption]]
value = "tag"
label = "Tag"
hint = "Tag description page"
path = "tags/${slug}"
[contentOption.labels]
title = "Tag Title:"
titleError = "Tag title is required"
