[a-table-with-a-white-board-and-white-pieces-of-paper-on-it-33xH9mk8kVs]
type = "unsplash"
plus = false
id = "33xH9mk8kVs"
artist = "micheile henderson"
url = "https://unsplash.com/@micheile"
detail = "https://unsplash.com/photos/a-table-with-a-white-board-and-white-pieces-of-paper-on-it-33xH9mk8kVs"

[a-forest-filled-with-lots-of-trees-covered-in-fog-ZFu48UY83fc]
type = "unsplash"
plus = true
id = "ZFu48UY83fc"
artist = "Degan Zakic"
url = "https://unsplash.com/@dejanzakic"
detail = "https://unsplash.com/photos/a-forest-filled-with-lots-of-trees-covered-in-fog-ZFu48UY83fc"

[persons-hand-over-brown-floral-field-during-daytime-UDleHDOhBZ8]
type = "unsplash"
plus = false
id = "UDleHDOhBZ8"
artist = "Daniel Jensen"
url = "https://unsplash.com/@dallehj"
detail = "https://unsplash.com/photos/persons-hand-over-brown-floral-field-during-daytime-UDleHDOhBZ8"

[a-close-up-of-a-cats-face-with-yellow-eyes-67HBaxCvA8M]
type = "unsplash"
plus = true
id = "67HBaxCvA8M"
artist = "Levi Meir Clancy"
url = "https://unsplash.com/@levimeirclancy"
detail = "https://unsplash.com/photos/a-close-up-of-a-cats-face-with-yellow-eyes-67HBaxCvA8M"

[polina-kuzovkova-Nzlzf7e3g8k-unsplash]
type = "unsplash"
plus = true
id = "Nzlzf7e3g8k"
artist = "Polina Kuzovkova"
url = "https://unsplash.com/@p_kuzovkova"
detail = "https://unsplash.com/photos/a-keyboard-and-a-mouse-on-a-table-Nzlzf7e3g8k"
