################################################################################
# hack: increasing timeout to prevent hugo from... timing out while recreating
# images. this is no more required for this website, because "we got RAM", but
# kept to find it when working on client projects.
# MUST be string, MUST contain digits and s for seconds, probably m for minutes
# (untested)
################################################################################
timeout = "600s"
