################################################################################
# see https://gohugo.io/configuration/output-formats/
################################################################################
[rss]
baseName = "rss"

[jsonfeed]
baseName = "feed"
isHTML = false
isPlainText = true
mediaType = "application/json"
noUgly = false
path = ""
permalinkable = false
protocol = ""
rel = "alternate"

[atom]
baseName = "atom"
isHTML = false
isPlainText = false
mediaType = "application/rss+xml"
noUgly = true
path = ""
permalinkable = false
protocol = ""
rel = "alternate"
