[dnb.feeds]
drafts = false
limit = 10
summary = true

[dnb.feeds.atom]
drafts = false
limit = 10
summary = true

[dnb.feeds.rss]
drafts = false
limit = 10
summary = true

[dnb.feeds.rss.webfeed]
# webfeed protocol
logo = ""
# 6 digit hex color code
accentColor = ""
coverImage = ""
icon = ""
[dnb.feeds.rss.webfeed.analytics]
enable = false
engine = "GoogleAnalytics" # currently GA only
id = "" # if left empty the global GA id will be used

[dnb.feeds.json]
drafts = false
limit = 10
summary = true

