name: Setup Playwright
description: Setup Playwright with caching
# inputs:
#   working-directory:
#     description: The working directory for the Playwright installation
#     required: true
runs:
  using: 'composite'
  steps:
    - name: Get Playwright version
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        echo "PLAYWRIGHT_VERSION=$(jq -r '.devDependencies["@playwright/test"]' package.json | sed 's/^[^0-9]*//')" >> $GITHUB_ENV

    - name: Cache Playwright
      id: playwright-cache
      uses: actions/cache@v5
      with:
        path: ~/.cache/ms-playwright
        key: 'playwright-browsers-${{ github.head_ref }}-${{ env.PLAYWRIGHT_VERSION }}'

    - name: Install Playwright browsers
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      # run: npx playwright install --with-deps chromium
      run: npx playwright install --with-deps
