on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
name: Linkinator Audit
jobs:
  linkinator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: JustinBeckwith/linkinator-action@v1
        with:
          paths: 'README.md'
          markdown: true
