---
name: contentreview

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  vale:
    name: runner/vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: errata-ai/vale-action@reviewdog
        with:
          vale_flags: "--config='.github/vale/.vale.ini'"

  remark-lint:
    name: runner / remark-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: google/wireit@setup-github-actions-caching/v1
      - name: install remark presets
        run: npm install remark-preset-lint-recommended
        shell: bash
      - name: remark-lint
        uses: reviewdog/action-remark-lint@v5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
