name: 'Check spelling'
on: # rebuild any PRs and main branch changes
  pull_request:
    branches-ignore:
      - "dependabot/**"
  push:

permissions:
  contents: read

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v4
      - uses: streetsidesoftware/cspell-action@v6
        with:
          inline: warning # default
          incremental_files_only: true # default
          strict: false
