name: Hugo Modules

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:

  update:
    runs-on: ubuntu-latest
    container:
      image: hugomods/hugo:go
    steps:
      - uses: actions/checkout@v4

      - name: Update modules
        run: hugo mod get -u

      - name: Tidy modules
        run: hugo mod tidy

      - uses: actions/upload-artifact@v4
        with:
          name: deps-hugo-modules
          path: |
            go.sum
            go.mod

  commit:
    needs: update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: deps-hugo-modules

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "chore(deps): update modules"
          branch: deps-hugo-modules
          title: Update Hugo Modules
