# TODO: check a way to load a list of URLs from JSON
# see https://github.com/treosh/lighthouse-ci-action/issues/95

name: Lighthouse CI

on: push

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: npm install

      - name: Wait for the Netlify Preview
        uses: jakepartusch/wait-for-netlify-action@v1
        id: netlify
        with:
          site_name: "kollitsch"

      - name: Audit URLs using Lighthouse for desktop
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            ${{ steps.netlify.outputs.url }}
            ${{ steps.netlify.outputs.url }}/page/2/
            ${{ steps.netlify.outputs.url }}/page/3/
          budgetPath: ./etc/lighthouse/budget.json
          configPath: ./etc/lighthouse/config-desktop.js
          uploadArtifacts: true
          temporaryPublicStorage: true
          runs: 3

      # - name: Webhook
      #   uses: denar90/webhook-action@0.1.1
      #   with:
      #     webhookUrl: ${{secrets.ACTION_WEBHOOK_URL}}
      #     data: '{ "links": ${{steps.LHCIAction.outputs.links}}, "manifest": ${{steps.LHCIAction.outputs.manifest}} }'

      - name: Audit URLs using Lighthouse for mobile
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            https://kollitsch.de/
            https://kollitsch.de/page/2/
            https://kollitsch.de/page/3/
          budgetPath: ./etc/lighthouse/budget.json
          configPath: ./etc/lighthouse/config-mobile.js
          uploadArtifacts: true
          temporaryPublicStorage: true
          runs: 3
