# TODO: check a way to load a list of URLs from JSON
# see https://github.com/treosh/lighthouse-ci-action/issues/95

name: Lighthouse CI

on: push

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            https://kollitsch.de/
            https://kollitsch.de/page/2/
            https://kollitsch.de/page/3/
          budgetPath: ./etc/lighthouse/budget.json
          uploadArtifacts: true
          temporaryPublicStorage: true
