on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

name: Daily Link Audit
jobs:
  linkinator:
    name: Link Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Node.js 12
        uses: actions/setup-node@v1
      - run: npm ci
      - run: npm run lint:links
