name: Stage production
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
  # schedule:
  #   # Run at 0815 daily
  #   - cron: '15 8 * * *'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK }}
